apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  namespace: admission-webhook
  name: mutate-cpu
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: mutate-pods.example.com
  clientConfig:
    service:
      name: mutate-cpu
      namespace: admission-webhook
      path: "/mutate"
      port: 443
  rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: Namespaced
  admissionReviewVersions:
    - v1
  sideEffects: None
  namespaceSelector:
    matchLabels:
      mutate-cpu: "true"
  failurePolicy: Fail
  timeoutSeconds: 3
